AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template runs appache server and displays a static webpage on a single EC2 instance. 
Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cebb45b34604efb8
      InstanceType: t2.micro
      KeyName: c1
      SecurityGroups:
       - SSH-HTTP
      UserData:
       'Fn::Base64': 
         !Sub |
          #!/bin/bash
          yum update -y
​
          # install apache
          yum install httpd -y 
            
          # start server sudo systemctl status httpd
          service httpd start
          chkconfig httpd on
          
          #getting index.html
          
          cd /var/www/html 
          sudo wget   
          sudo wget 
          sudo wget 
          sudo wget 
